name: "Memos Production Deploy"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "memos"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug build context
        run: |
          pwd
          ls
          ls app || true
          ls app/memos || true
          ls app/memos/cmd || true
          ls app/memos/cmd/memos || true

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::304321521963:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        id: build-image
        working-directory: ${{ github.workspace }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: memos
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --no-cache -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve -var="image_tag=${{ github.sha }}"

      - name: Wait for ECS & Health Check
        run: |
          aws ecs wait services-stable \
            --cluster memos-ecs-cluster \
            --services memos-service
          curl --fail https://tm.ahmedo.co.uk
          
